package com.lacity.aipppc.service;

import com.lacity.aipppc.dto.screening.ClearanceDto;
import com.lacity.aipppc.dto.screening.FindingDto;
import com.lacity.aipppc.dto.screening.RunDetailDto;
import com.lacity.aipppc.model.Project;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Generates the exportable PDF compliance report (SOW 2.2.8 — readiness status,
 * findings, likely clearances, explanations/references, and next steps, exported
 * via native in-system functionality). The report leads with the advisory-only
 * disclaimer (SOW 2.2.9) and carries the Universal Project ID for continuity into
 * Formal Plan Check.
 */
@Service
public class ReportService {

    private static final Logger log = LoggerFactory.getLogger(ReportService.class);
    private static final PDType1Font FONT = new PDType1Font(Standard14Fonts.FontName.HELVETICA);
    private static final PDType1Font BOLD = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
    private static final float MARGIN = 54;
    private static final float WIDTH = PDRectangle.LETTER.getWidth() - 2 * MARGIN;

    public byte[] generate(Project project, RunDetailDto detail) {
        try (PDDocument doc = new PDDocument(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Cursor c = new Cursor(doc);

            c.text("City of Los Angeles — Department of Building and Safety", BOLD, 14);
            c.text("AI-Powered Pre-Plan Check Assistant — Compliance Report", BOLD, 12);
            c.gap(6);
            c.text("Universal Project ID: " + project.getUniversalProjectId(), BOLD, 11);
            c.text("Project: " + safe(project.getTitle()), FONT, 10);
            c.text("Permit type: " + safe(project.getPermitTypeCode())
                + (project.getAddress() != null ? "   |   Address: " + project.getAddress() : ""), FONT, 10);
            if (project.getParcel() != null) {
                c.text("Zone: " + safe(project.getParcel().getZone()) + "   |   APN: " + safe(project.getApn()), FONT, 10);
            }
            c.text("Generated: " + ZonedDateTime.now(ZoneId.of("America/Los_Angeles"))
                .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm z")), FONT, 9);
            c.gap(6);

            // Advisory disclaimer (SOW 2.2.9).
            c.box("ADVISORY ONLY — This report is generated by an AI-assisted tool and does NOT "
                + "constitute Formal Plan Check approval. Final determinations, including required "
                + "clearances, are made solely by City of Los Angeles staff.");
            c.gap(6);

            var run = detail.run();
            c.text("Submission Readiness: " + humanize(run.readinessStatus())
                + "  (score " + (run.readinessScore() == null ? "n/a" : run.readinessScore() + "/100") + ")", BOLD, 12);
            c.text(run.blockingCount() + " blocking, " + run.warningCount() + " warning, "
                + run.infoCount() + " informational finding(s); " + run.clearanceCount()
                + " likely clearance(s).", FONT, 10);
            if (run.aiProviderUsed() != null) {
                c.text("AI augmentation: " + run.aiProviderUsed()
                    + (run.aiModelUsed() != null ? " (" + run.aiModelUsed() + ")" : "")
                    + "   |   Code basis: " + safe(run.codeVersion()), FONT, 9);
            }
            c.gap(8);

            // Findings.
            c.text("Findings", BOLD, 12);
            if (detail.findings().isEmpty()) {
                c.text("No findings identified.", FONT, 10);
            } else {
                for (FindingDto f : detail.findings()) {
                    c.text("[" + f.severity() + " · " + f.category() + " · conf " + f.confidence()
                        + "% " + f.confidenceLevel() + "] " + f.title(), BOLD, 10);
                    c.wrapped(f.description(), FONT, 9);
                    if (f.codeReference() != null) c.wrapped("Code: " + f.codeReference(), FONT, 9);
                    if (f.recommendation() != null) c.wrapped("Recommendation: " + f.recommendation(), FONT, 9);
                    c.gap(4);
                }
            }
            c.gap(6);

            // Clearances.
            c.text("Likely Required Clearances", BOLD, 12);
            if (detail.clearances().isEmpty()) {
                c.text("No departmental clearances identified.", FONT, 10);
            } else {
                for (ClearanceDto cl : detail.clearances()) {
                    c.text("[" + cl.department() + " · conf " + cl.confidence() + "% "
                        + cl.confidenceLevel() + "] " + cl.clearanceName(), BOLD, 10);
                    c.wrapped(cl.reason(), FONT, 9);
                    if (cl.submittalRequirements() != null && !cl.submittalRequirements().isEmpty()) {
                        c.wrapped("Submittal requirements: " + String.join("; ", cl.submittalRequirements()), FONT, 9);
                    }
                    if (cl.infoUrl() != null) c.wrapped("More info: " + cl.infoUrl(), FONT, 9);
                    c.gap(4);
                }
            }
            c.gap(6);

            c.text("Next Steps", BOLD, 12);
            for (String step : nextSteps(run.readinessStatus())) {
                c.wrapped("• " + step, FONT, 10);
            }

            c.close();
            doc.save(out);
            return out.toByteArray();
        } catch (Exception e) {
            log.error("Report generation failed: {}", e.getMessage(), e);
            throw new IllegalStateException("Could not generate the compliance report.");
        }
    }

    private List<String> nextSteps(String status) {
        if ("READY_FOR_SUBMISSION".equals(status)) {
            return List.of("Your submission appears ready. Proceed to a Formal Plan Check submission in ePlanLA.",
                "Carry this Universal Project ID forward so staff can link your pre-check results.",
                "Begin obtaining any likely clearances listed above in parallel.");
        }
        if ("INCOMPLETE".equals(status)) {
            return List.of("Upload the missing required documents identified above.",
                "Re-run the pre-plan check to confirm completeness before submitting.",
                "Contact LADBS Development Services if you need help identifying required documents.");
        }
        return List.of("Review and address the blocking and warning findings above.",
            "Consult the cited code sections; adjust plans as needed.",
            "Re-run the pre-plan check, then proceed to ePlanLA when ready.");
    }

    private String humanize(String status) {
        if (status == null) return "Not Assessed";
        return switch (status) {
            case "READY_FOR_SUBMISSION" -> "Ready for Submission";
            case "REQUIRES_ATTENTION" -> "Requires Attention";
            case "INCOMPLETE" -> "Incomplete";
            default -> "Not Assessed";
        };
    }

    private String safe(String s) { return s == null ? "" : s; }

    /** Minimal text-layout cursor over a growing set of PDF pages. */
    private static final class Cursor {
        private final PDDocument doc;
        private PDPage page;
        private PDPageContentStream cs;
        private float y;

        Cursor(PDDocument doc) throws Exception {
            this.doc = doc;
            newPage();
        }

        private void newPage() throws Exception {
            if (cs != null) cs.close();
            page = new PDPage(PDRectangle.LETTER);
            doc.addPage(page);
            cs = new PDPageContentStream(doc, page);
            y = PDRectangle.LETTER.getHeight() - MARGIN;
        }

        private void ensure(float needed) throws Exception {
            if (y - needed < MARGIN) newPage();
        }

        void text(String s, PDType1Font font, float size) throws Exception {
            ensure(size + 4);
            cs.beginText();
            cs.setFont(font, size);
            cs.newLineAtOffset(MARGIN, y);
            cs.showText(sanitize(s));
            cs.endText();
            y -= size + 4;
        }

        void wrapped(String s, PDType1Font font, float size) throws Exception {
            if (s == null) return;
            for (String line : wrap(sanitize(s), font, size, WIDTH)) {
                text(line, font, size);
            }
        }

        void box(String s, PDType1Font... ignore) throws Exception {
            wrapped(s, BOLD, 9);
        }

        void gap(float g) { y -= g; }

        void close() throws Exception { if (cs != null) cs.close(); }

        private List<String> wrap(String text, PDType1Font font, float size, float maxWidth) throws Exception {
            java.util.List<String> lines = new java.util.ArrayList<>();
            for (String paragraph : text.split("\n")) {
                StringBuilder line = new StringBuilder();
                for (String word : paragraph.split(" ")) {
                    String candidate = line.isEmpty() ? word : line + " " + word;
                    float w = font.getStringWidth(candidate) / 1000 * size;
                    if (w > maxWidth && !line.isEmpty()) {
                        lines.add(line.toString());
                        line = new StringBuilder(word);
                    } else {
                        line = new StringBuilder(candidate);
                    }
                }
                lines.add(line.toString());
            }
            return lines;
        }

        /** Standard-14 fonts are WinAnsi; strip anything they can't encode. */
        private String sanitize(String s) {
            if (s == null) return "";
            return s.replace("—", "-").replace("–", "-").replace("’", "'")
                .replace("“", "\"").replace("”", "\"").replace("•", "-")
                .replaceAll("[^\\x20-\\x7E]", "");
        }
    }
}
